import {ComboBox, Button} from "std-widgets.slint";
import {S_Action} from "./structs.slint";
export component ActionInputPopup inherits PopupWindow {
  callback on_confirm( S_Action);
  callback on_cancel;
  property <S_Action> action: {action_type: "", action_info: ""};
  close-on-click: false;
  public function to_s_action() -> S_Action {
    action.action_type = selector.current-value;
    action.action_info = input.text;
    return action;
  }
  
  states [
      active when selector.current-value == "Rename": {
        input.visible: true;
      }
      active when selector.current-value == "Randomize": {
        input.visible: false;
      }
  ]
  VerticalLayout {
    HorizontalLayout {
    selector := ComboBox {
      model: ["Randomize", "Rename"];
    }
      input := TextInput {}

    }
    HorizontalLayout {
      Button {
        text: "Confirm";
        clicked => {root.on_confirm( to_s_action())} 
      }
      Button {
        text: "Cancel";
        clicked => {root.on_cancel()}
      }
    }
  }
}
