[package]
name = "renamer_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
env_logger = "0.11.8"
log = "0.4.27"
nom = "8.0.0"
rand = "0.9.1"
rayon = "1.10.0"
regex = "1.11.1"
thiserror = "2.0.12"
